services:
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:5432"

  cassandra_bp:
    image: bitnami/cassandra:latest
    restart: unless-stopped
    environment:
      CASSANDRA_AUTHENTICATOR: PasswordAuthenticator
      CASSANDRA_USER: ${CASSANDRA_USERNAME}
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
      CASSANDRA_PASSWORD_SEEDER: yes
    ports:
      - "${CASSANDRA_PORT}:9042"
